server:
  port: 8001

spring:

  application:
    name : GCS_Etudiant
  datasource:
    url: jdbc:postgresql://localhost:5432/GCS_Etudiant
    username: postgres
    password: post123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
